name: Build & Deploy Landing

on:
  push:
    branches:
      - main   #branch to deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ðŸ— Build Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/mw-landing:latest"
          docker build -t "$IMAGE" .

      - name: ðŸ“¤ Push Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/mw-landing:latest"
          docker push "$IMAGE"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ðŸ” Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: ðŸš€ Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
            set -e
            cd /home/ubuntu/apps
            docker compose pull landing
            docker compose up -d landing
            docker image prune -af || true
          EOF
